### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by Niels1006** [mob41/ev3dev-lang-java#16]
If I try to launch the compiled .jar (with IntelliJ) on my Brick it gives me this Error:

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

SLF4J: Defaulting to no-operation (NOP) logger implementation

SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`

It appears if I try to use Motors, Sensors and so on, e.g.
`Motor m = new Motor(new LegoPort(LegoPort.OUTPUT_A))`

And I am a beginner with ev3dev java, so don't be too harsh :)

Thank you 💯

**Comment by a1aw** [comment]
This is just a warning message that won't affect the functionality. You can probably ignore it. This appears if the logger does not find any SLF4J provider in your application. Probably you did not add a dependency of slf4j-api and a logger e.g. slf4j-log4j.

For more details you can check what the log provided http://www.slf4j.org/codes.html#StaticLoggerBinder

**Comment by Niels1006** [comment]
Thank you :)
But my Motor doesn't work anyways :(.
Would this work if I connect a M/L Motor to OUTPUT_A?

`Motor m = new Motor(new LegoPort(LegoPort.OUTPUT_A));
m.setDutyCycleSP(50);
m.runForever();`
Edit: It works, I changed DutyCycle_SP to Speed_SP

**Comment by a1aw** [comment]
Sorry for late reply. In newer kernel version, DutyCycle_SP() is not applicable to runForever() now. To set speed, you have to use setSpeed_SP()

http://www.jev3dev.tk/getting_started-tank.html
